### ISSUE TITLE
D:\anaconda\envs\pythonProject\python.exe "D:\i PYTHON\pythonProject\Espresso.py"  Traceback (most recent call last):   File "D:\i PYTHON\pythonProject\Espresso.py", line 1, in <module>     from pyswmm import Simulation   File "D:\i PYTHON\pythonProject\pyswmm-master\pyswmm\__init__.py", line 11, in <module>     import pyswmm._monkey_patch   File "D:\i PYTHON\pythonProject\pyswmm-master\pyswmm\_monkey_patch.py", line 18, in <module>     from swmm.toolkit import __version__ as _tk_version ModuleNotFoundError: No module named 'swmm'  Process finished with exit code 1

### ISSUE THREAD

**Issue by cui-hanwu** [pyswmm/pyswmm#549]
D:\anaconda\envs\pythonProject\python.exe "D:\i PYTHON\pythonProject\Espresso.py" 
Traceback (most recent call last):
  File "D:\i PYTHON\pythonProject\Espresso.py", line 1, in <module>
    from pyswmm import Simulation
  File "D:\i PYTHON\pythonProject\pyswmm-master\pyswmm\__init__.py", line 11, in <module>
    import pyswmm._monkey_patch
  File "D:\i PYTHON\pythonProject\pyswmm-master\pyswmm\_monkey_patch.py", line 18, in <module>
    from swmm.toolkit import __version__ as _tk_version
ModuleNotFoundError: No module named 'swmm'

Process finished with exit code 1

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - Python Version [e.g. Python 3.6-x86]
 - PySWMM Version [e.g. v0.4.8]

**Additional context**

**Comment by bemcdonnell** [comment]
@cui-hanwu,

Can you please provide the additional information that we need in the issue?

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - Python Version [e.g. Python 3.6-x86]
 - PySWMM Version [e.g. v0.4.8]

**Additional context**
Add any other context about the problem here.
