### ISSUE TITLE
Update conda-forge to V2

### ISSUE THREAD

**Issue by cheginit** [pyswmm/pyswmm#551]
The `conda-forge` version is way out of date (v0.6). I'd appreciate it, if it can be updated to the latest version with support for `osx-arm64`. I am publishing a package on `conda-forge` that depends on `pyswmm` and `osx` builds [fail](https://github.com/conda-forge/staged-recipes/pull/27704) due to `pyswmm` being out of date and not supporting the latest versions.

**Comment by lrntct** [comment]
Hi. I would gladly review a PR to update to the last release and update the maintainer list as well.

**Comment by cheginit** [comment]
Awesome! I looked at the feedstock and current version of `pyswmm` and realized that the main issue is that `pyswmm` now depends on `swmm-toolkit` instead of `swmm`. As far as I can tell, `swmm-toolkit` is not on `conda-forge`. So first, `swmm-toolkit` needs to be added to `conda-forge` and then updating `pyswmm` on `conda-forge` will be trivial. So, I guess the main question is if there's any plan to add `swmm-toolkit` to `conda-forge`? I'd be happy to help with adding `swmm-toolkit`, but I am not very familiar with its build process.

**Comment by lrntct** [comment]
@bemcdonnell I haven't built anything on conda-forge in a few years. Therefore, I doubt I would be able to provide meaningful help.

**Comment by cheginit** [comment]
I can help with the `conda-forge` side of things as I manage several `conda-forge` packages. However, I'd need help with replicating the build process of `swmm-toolkit` on `conda-forge` from someone in the `pyswmm` team who has a good understanding of `swmm-toolkit`'s build workflow.

**Comment by karosc** [comment]
I attempted to get conda-forge to build swmm-toolkit last year when we change the swmm-toolkit build process to use cibuildwheel. I thought if I could get pip to properly build swmm-toolkit from an sdist, getting it on conda-forge would be a one click. However, I gave up I think due to dependency issues, I can't remember exactly. 

@cheginit, if you can get a successful conda-forge build on all 3 platforms (mac, windows, and linux) using [my fork](https://github.com/karosc/staged-recipes/tree/swmm-toolkit) as a starting point, then we can consider supporting a conda-forge package. I even opened up [a PR into staged-recipes ](https://github.com/conda-forge/staged-recipes/pull/23013)that I never followed through with that you can just pick up if you'd like.

**Comment by cheginit** [comment]
@karosc Thanks. I will give it a try.

First issue that I faced is lack of the source distribution archive on `pypi` after 0.15.2 for `swmm-toolkit`. I think there are some issues in your `pypi` publish workflow that stopped uploading source distribution archive on `pypi` along with the wheels since 0.15.3. For now, I will try to see if I can get it to work locally for `swmm-toolkit=0.15.2` until `sdist` is added to its `pypi`.

**Comment by cheginit** [comment]
@karosc now that `swmm-toolkit` has been added to conda-forge, it'd be great if `pyswmm`'s feedstock gets a new release.

**Comment by cheginit** [comment]
Thank you all for working with me to push this to the finish line!
